version: "3"
services:
  app-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=pizza
      - MYSQL_DATABASE=cuong
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db